[ 2025-03-05 06:25:00,510 ] root - INFO - Loading object from artifact/data_transformation/preprocessor.pkl
[ 2025-03-05 06:25:00,948 ] root - INFO - Preprocessor loaded successfully
[ 2025-03-05 06:25:00,948 ] root - INFO - Loading object from artifact/model_training/model.pkl.zip
[ 2025-03-05 06:25:01,361 ] root - INFO - Model loaded successfully
[ 2025-03-05 06:25:01,362 ] root - INFO - Loading schema from config/schema.yaml
[ 2025-03-05 06:25:01,366 ] root - INFO - Schema loaded successfully
[ 2025-03-05 06:25:01,400 ] werkzeug - WARNING -  * Debugger is active!
[ 2025-03-05 06:25:01,411 ] werkzeug - INFO -  * Debugger PIN: 145-691-381
[ 2025-03-05 06:25:48,358 ] werkzeug - INFO - 127.0.0.1 - - [05/Mar/2025 06:25:48] "[33mGET / HTTP/1.1[0m" 404 -
[ 2025-03-05 06:25:59,911 ] werkzeug - INFO - 127.0.0.1 - - [05/Mar/2025 06:25:59] "[31m[1mGET /predict HTTP/1.1[0m" 405 -
[ 2025-03-05 06:26:22,297 ] werkzeug - INFO - 127.0.0.1 - - [05/Mar/2025 06:26:22] "POST /test HTTP/1.1" 200 -
[ 2025-03-05 06:29:30,866 ] root - INFO - Preprocessing input data
[ 2025-03-05 06:29:30,866 ] root - INFO - Loading schema from config/schema.yaml
[ 2025-03-05 06:29:30,872 ] root - INFO - Extracting schema columns
[ 2025-03-05 06:29:30,898 ] root - INFO - Making predictions
[ 2025-03-05 06:29:30,899 ] root - INFO - Loading object from artifact/data_transformation/preprocessor.pkl
[ 2025-03-05 06:29:30,901 ] root - INFO - Loading object from artifact/model_training/model.pkl.zip
[ 2025-03-05 06:29:31,320 ] root - INFO - Preprocessing input data
[ 2025-03-05 06:29:31,320 ] root - INFO - Loading schema from config/schema.yaml
[ 2025-03-05 06:29:31,322 ] root - INFO - Extracting schema columns
[ 2025-03-05 06:29:31,323 ] root - WARNING - yr_of_estab column not found in input data.
[ 2025-03-05 06:29:31,323 ] root - ERROR - Error preprocessing input data: Error occurred python script name [/Users/mirza/Desktop/mirza7865-USVisa-MLOps-ProductionGrade/app.py] line number [73] error message ["['case_id', 'yr_of_estab'] not found in axis"]
[ 2025-03-05 06:29:31,323 ] root - ERROR - Error making predictions: Error occurred python script name [/Users/mirza/Desktop/mirza7865-USVisa-MLOps-ProductionGrade/app.py] line number [93] error message [Error occurred python script name [/Users/mirza/Desktop/mirza7865-USVisa-MLOps-ProductionGrade/app.py] line number [73] error message ["['case_id', 'yr_of_estab'] not found in axis"]]
[ 2025-03-05 06:29:31,323 ] root - ERROR - Error: Error occurred python script name [/Users/mirza/Desktop/mirza7865-USVisa-MLOps-ProductionGrade/app.py] line number [93] error message [Error occurred python script name [/Users/mirza/Desktop/mirza7865-USVisa-MLOps-ProductionGrade/app.py] line number [73] error message ["['case_id', 'yr_of_estab'] not found in axis"]]
[ 2025-03-05 06:29:31,333 ] werkzeug - INFO - 127.0.0.1 - - [05/Mar/2025 06:29:31] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
[ 2025-03-05 06:30:57,272 ] werkzeug - INFO -  * Detected change in '/Users/mirza/Desktop/mirza7865-USVisa-MLOps-ProductionGrade/test.py', reloading
